### ISSUE TITLE
Unhandled JavaScript exception

### ISSUE THREAD

**Issue by probonopd** [TooFiveFive/newlogic#12]
Downloaded and ran the AppImage on a system on which this software was never running before. Getting

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/travis/.config/newlogic/Settings'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.writeFileSync (fs.js:1311:33)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:1329:5)
    at __webpack_require__ (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:21:30)
    at Object.module.exports.__webpack_require__.app.app (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:1293:18)
    at __webpack_require__ (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:21:30)
    at /run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8795/app/resources/app.asar/main.js:6065:3)
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1614 (detailed logs linked there)

**Comment by ericm** [comment]
Looks like an issue in the main.js. 
I'll look into this. I think it's just an issue with the function that's supposed to create the settings file.
Should be fixed in the next release.

**Comment by ericm** [comment]
This will be packaged with version 0.1.4-beta

**Comment by probonopd** [comment]
Please ping me once a new release is out so that I can re-run the test, thanks.

**Comment by ericm** [comment]
@probonopd https://github.com/ericm/newlogic/releases/tag/v0.1.4-beta
